# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=7)),
                ('career', models.CharField(max_length=1)),
                ('grade', models.CharField(max_length=3)),
                ('major', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name', 'facebookid')]),
        ),
    ]
