# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=100, unique=True)),
                ('credits', models.IntegerField(default=1)),
                ('title', models.CharField(default='', max_length=100)),
                ('professor', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('intern_location', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('obligatory', models.BooleanField(default=True)),
                ('language', models.CharField(default='', max_length=100)),
                ('prerequisite', models.CharField(default='', max_length=100)),
                ('note', models.CharField(default='', max_length=100)),
                ('discipline', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100)),
                ('degree', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20)),
                ('code', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
