# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedcourse',
            name='user',
        ),
        migrations.AddField(
            model_name='selectedcourse',
            name='semester',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='selectedcourse',
            name='user_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='selectedcourse',
            name='code',
            field=models.CharField(default='', max_length=64),
        ),
    ]
